services:
  # Landing page (static)
  - type: web
    name: landing-kian-main
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    domains:
      - landing-kian.onrender.com
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
  # Panel de administración (web service)
  - type: web
    name: landing-kian-auth
    env: node
    region: oregon
    buildCommand: cd proyecto/auth && npm install
    startCommand: cd proyecto/auth && npm run start
    pullRequestPreviewsEnabled: true
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
      - key: NODE_ENV
        value: production
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
  # Calculadora (web service)
  - type: web
    name: landing-kian-calc
    env: node
    region: oregon
    buildCommand: cd proyecto/calc && npm install
    startCommand: cd proyecto/calc && npm run start
    pullRequestPreviewsEnabled: true
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
      - key: NODE_ENV
        value: production
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
